# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\"5\n\x0fViewPostRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\"#\n\x10ViewPostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n\x0fLikePostRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\"#\n\x10LikePostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"F\n\x12\x43ommentPostRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\")\n\x13\x43ommentPostResponse\x12\x12\n\ncomment_id\x18\x01 \x01(\t\"F\n\x12GetCommentsRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"Q\n\x07\x43omment\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"K\n\x13GetCommentsResponse\x12\x1f\n\x08\x63omments\x18\x01 \x03(\x0b\x32\r.post.Comment\x12\x13\n\x0btotal_pages\x18\x02 \x01(\x05\x32\x8b\x02\n\x0bPostService\x12\x39\n\x08ViewPost\x12\x15.post.ViewPostRequest\x1a\x16.post.ViewPostResponse\x12\x39\n\x08LikePost\x12\x15.post.LikePostRequest\x1a\x16.post.LikePostResponse\x12\x42\n\x0b\x43ommentPost\x12\x18.post.CommentPostRequest\x1a\x19.post.CommentPostResponse\x12\x42\n\x0bGetComments\x12\x18.post.GetCommentsRequest\x1a\x19.post.GetCommentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIEWPOSTREQUEST']._serialized_start=20
  _globals['_VIEWPOSTREQUEST']._serialized_end=73
  _globals['_VIEWPOSTRESPONSE']._serialized_start=75
  _globals['_VIEWPOSTRESPONSE']._serialized_end=110
  _globals['_LIKEPOSTREQUEST']._serialized_start=112
  _globals['_LIKEPOSTREQUEST']._serialized_end=165
  _globals['_LIKEPOSTRESPONSE']._serialized_start=167
  _globals['_LIKEPOSTRESPONSE']._serialized_end=202
  _globals['_COMMENTPOSTREQUEST']._serialized_start=204
  _globals['_COMMENTPOSTREQUEST']._serialized_end=274
  _globals['_COMMENTPOSTRESPONSE']._serialized_start=276
  _globals['_COMMENTPOSTRESPONSE']._serialized_end=317
  _globals['_GETCOMMENTSREQUEST']._serialized_start=319
  _globals['_GETCOMMENTSREQUEST']._serialized_end=389
  _globals['_COMMENT']._serialized_start=391
  _globals['_COMMENT']._serialized_end=472
  _globals['_GETCOMMENTSRESPONSE']._serialized_start=474
  _globals['_GETCOMMENTSRESPONSE']._serialized_end=549
  _globals['_POSTSERVICE']._serialized_start=552
  _globals['_POSTSERVICE']._serialized_end=819
# @@protoc_insertion_point(module_scope)
